services:
  postgres:
    image: postgres:16-alpine
    container_name: carshop-postgres
    environment:
      POSTGRES_DB: carshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - carshop-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: carshop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carshop-api
    ports:
      - "5107:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=carshop;Username=postgres;Password=password"
      Redis__ConnectionString: "redis:6379"
      jwt__key: "asdbfjdlvfdkopsfvnjvbsh37rtgf92uebhfjewef9e4ub3gkj"
      jwt__issuer: "CarShop"
      jwt__audience: "CarShopUsers"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - carshop-uploads:/app/wwwroot/uploads
    restart: unless-stopped

volumes:
  carshop-pgdata:
  carshop-uploads:
